DOCSP-17236 drawer pages
mongodb/docs-java pull request #120
Opened 2021-07-01 21:37 UTC by kyuan-mongodb

## Pull Request Info
Added drawer pages for the following API pages: Bson, Core, Sync

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-17236

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17236-SeparateAPIDocLinks/

### Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Does it render on staging correctly?
- [x] Are all the links working?
- [x] Are the staging links in the PR description updated?

### If your page documents a concept, does it meet the following criteria?

- [ ] Target the [Jasmin persona](https://drive.google.com/file/d/14FbBOLCVxwSP6M9BK4Nz1Ir9tzxT8_02/view)
- [ ] Target the [Lucas persona](https://drive.google.com/file/d/1J2vqJxo7ldv7OP_obA9Q-avf0o_ju4Lk/view)

2021-07-01 22:46 UTC, ccho-mongodb requested changes

2021-07-01 22:46 UTC, ccho-mongodb commented on source/api-documentation.txt
> +    Sync Driver API <http://mongodb.github.io/mongo-java-driver/4.3/apidocs/mongodb-driver-sync/index.html>
Would it be better to use the titles from the current Java docs?
https://mongodb.github.io/mongo-java-driver/4.2/apidocs/
E.g.
Bson
Core
Java Driver (modern API)
Java Driver (legacy API)
I think we also refer to the last one somewhere in the docs, so we might include that if so.

2021-07-02 14:57 UTC, ccho-mongodb approved these changes
LGTM!

2021-07-02 14:58 UTC, kyuan-mongodb commented
Hi @jyemin and @rozza , We want to make sure you're okay with the naming of the drawer pages.

2021-07-02 15:01 UTC, jyemin commented
If they match what we have currently, then LGTM

2021-07-02 15:34 UTC, merged