DOCSP-17218 what's new in 4.3
mongodb/docs-java pull request #121
Opened 2021-07-02 15:17 UTC by kyuan-mongodb

## Pull Request Info
Added information on What's New in 4.3.

Reference used: https://mongodb.github.io/mongo-java-driver/4.3/whats-new/ 

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-17218

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-17218-WhatsNew4.3/whats-new/

### Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Does it render on staging correctly?
- [x] Are all the links working?
- [x] Are the staging links in the PR description updated?

### If your page documents a concept, does it meet the following criteria?

- [ ] Target the [Jasmin persona](https://drive.google.com/file/d/14FbBOLCVxwSP6M9BK4Nz1Ir9tzxT8_02/view)
- [ ] Target the [Lucas persona](https://drive.google.com/file/d/1J2vqJxo7ldv7OP_obA9Q-avf0o_ju4Lk/view)

2021-07-07 02:11 UTC, terakilobyte requested changes
This will need to incorporate the recent changes [here](https://github.com/mongodb/mongo-java-driver/pull/747/files#diff-bd319b7724ba91e97cc65d8d4d8d3bec052c6190388f122c7e41b36856b206d7R31-R33) and [here](https://github.com/mongodb/mongo-java-driver/blob/master/docs/reference/content/whats-new.md).

This ticket may be in a state of "waiting" up until .live

2021-07-09 20:51 UTC, terakilobyte approved these changes
lgtm

2021-07-09 20:57 UTC, kyuan-mongodb commented
Hi @jyemin and @rozza, I want to make sure the content in this PR is technically correct.

2021-07-12 10:37 UTC, rozza approved these changes

2021-07-12 14:52 UTC, stIncMale requested changes
I have only one concern. Please note that I do not have knowledge to review the changes with regard to removing restrictions on allowed characters.

2021-07-12 14:52 UTC, stIncMale commented on source/whats-new.txt
> +- The ``maxConnecting`` property limiting the number of connections you create in a connection pool
This a constant that cannot be changed neither via public nor via non-advertised means. I have doubts this change is supposed to be documented. But even if it is, we should only say that we limited the rate of establishing new TCP connections per server socket.

2021-07-12 15:11 UTC, stIncMale approved these changes

2021-07-12 15:12 UTC, merged

2021-07-12 15:12 UTC, jyemin requested changes

2021-07-12 15:12 UTC, jyemin commented on source/whats-new.txt
>  - Added ``snapshot`` (non-speculative) as a ``readConcern`` level for read commands outside of transactions
This isn't completely accurate: that read concern level was actually added a long time ago.  The new feature is (indirect) support for `atClusterTime` for the read concern, which is supported via a new ClientSessionOption.

2021-07-12 15:12 UTC, jyemin commented
@kyuan-mongodb I was in the process of reviewing this when you merged it.