DOCSP-28808: conversion operations
mongodb/docs-java pull request #358
Opened 2023-03-27 20:36 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-java/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-28808
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/java/docsworker-xlarge/DOCSP-28808-conversion-operations/fundamentals/aggregation/aggregation-expression-operations/#conversion-operations)

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [x] Are all the links working?

2023-03-27 23:45 UTC, DBirtolo-mdb requested changes
Nice start. Just a couple of minor tweaks recommended.

2023-03-27 23:45 UTC, DBirtolo-mdb commented on source/fundamentals/aggregation/aggregation-expression-operations.txt
> +     - :manual:`$toDate </reference/operator/aggregation/toDate/>`
I'd recommend putting these in alphabetical order so it is easier for readers to follow.

```suggestion
   * - `millisecondsAsDate() <{+api+}/apidocs/mongodb-driver-core/com/mongodb/client/model/mql/MqlInteger.html#millisecondsAsDate()>`__
     - :manual:`$toDate </reference/operator/aggregation/toDate/>`

   * - `parseDate() <{+api+}/apidocs/mongodb-driver-core/com/mongodb/client/model/mql/MqlString.html#parseDate()>`__
     - :manual:`$dateFromString </reference/operator/aggregation/dateFromString/>`

   * - `parseInteger() <{+api+}/apidocs/mongodb-driver-core/com/mongodb/client/model/mql/MqlString.html#parseInteger()>`__
     - :manual:`$toInt </reference/operator/aggregation/toInt/>`
```

2023-03-27 23:45 UTC, DBirtolo-mdb commented on source/fundamentals/aggregation/aggregation-expression-operations.txt
> +their graduation years, which are stored as strings. You want to add a
[suggestion]

For readability, I'd recommend a slight rewording. You could also break this into two sentences, but that's totally up to you.

```suggestion
Suppose you have a collection of students with their graduation years
stored as strings and want to calculate the years for their fifth reunions.
You want to add a
```

2023-03-30 21:09 UTC, katcharov requested changes

2023-03-31 17:20 UTC, katcharov approved these changes
LGTM

2023-03-31 17:21 UTC, merged