[JAVA] Relax the CMAP documentation requirement for durations in events
mongodb/docs-java pull request #501
Opened 2024-01-15 21:34 UTC by rachel-mack

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-java/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-35270>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-01-16 16:48 UTC, mongoKart requested changes

2024-01-16 16:48 UTC, mongoKart commented on source/whats-new.txt
> +
I think more technical detail would be helpful here. I'd probably just paste in the Jira notes and maybe edit them slightly.

Also, I think the ticket describes more changes than I see here; is there another ticket for those?

2024-01-17 16:25 UTC, rachel-mack commented
Note: Vale error is for use of "Fail" in the event name.

2024-01-17 19:45 UTC, mongoKart requested changes
just a couple quick changes!

2024-01-17 19:45 UTC, mongoKart commented on source/whats-new.txt
> +  includes the time taken to deliver the ``ConnectionPoolListener``. That is,
I: per ticket, i think this should be:

```suggestion
  includes the time taken to deliver the ``ConnectionCreatedEvent``. That is,
```

2024-01-17 19:45 UTC, mongoKart commented on source/whats-new.txt
> +- The ``getElapsedTime`` method on ``com.mongodb.event.ConnectionReadyEvent``
I: In all of our docs that I've seen, we suffix method names with parentheses

```suggestion
- The ``getElapsedTime()`` method on ``com.mongodb.event.ConnectionReadyEvent``
```

2024-01-17 19:45 UTC, mongoKart commented on source/whats-new.txt
> +  ``com.mongodb.event.ConnectionPoolListener.connectionCreated``.
```suggestion
  the time returned includes the duration of the
  ``com.mongodb.event.ConnectionPoolListener.connectionCreated()`` method.
```

2024-01-17 19:45 UTC, mongoKart commented on source/whats-new.txt
> +  The ``getElapsedTime`` methods on
```suggestion
  The ``getElapsedTime()`` methods on
```

2024-01-17 19:45 UTC, mongoKart commented on source/whats-new.txt
> +  ``com.mongodb.eventConnectionPoolListener.connectionCheckOutStarted``.
```suggestion
  time returned includes the duration of the
  ``com.mongodb.eventConnectionPoolListener.connectionCheckOutStarted()`` method.
```

2024-01-18 19:43 UTC, mongoKart approved these changes
LGTM

2024-01-18 19:49 UTC, merged