DOCSP-4079: GridFS write concern
mongodb/docs-java pull request #547
Opened 2024-05-29 15:20 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-java/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-4079
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-05-29 15:52 UTC, mcmorisi approved these changes
LGTM!

2024-05-31 21:41 UTC, stIncMale requested changes

2024-05-31 21:41 UTC, stIncMale commented on source/fundamentals/gridfs.txt
> +   When storing files in a GridFS bucket, ensure that you use the default ``WriteConcern.MAJORITY``
```suggestion
   When storing files in a GridFS bucket, ensure that you use the ``WriteConcern.MAJORITY``
```

2024-06-03 15:32 UTC, stIncMale approved these changes

2024-06-06 15:24 UTC, merged