DOCSP-44901 TOC Relabel
mongodb/docs-java pull request #589
Opened 2024-11-09 00:20 UTC by lindseymoore

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-java/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-44901>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-11-11 15:40 UTC, mongoKart approved these changes
LGTM w/ a few suggestions

2024-11-11 15:40 UTC, mongoKart commented on source/fundamentals/connection.txt
> +   Connect with AWS Lambda <https://www.mongodb.com/docs/atlas/manage-connections-aws-lambda/>
Since this is in the connection guide, it seems reasonable to call this "AWS Lambda"

2024-11-11 15:40 UTC, mongoKart commented on source/fundamentals/crud.txt
> +   Write Operations </fundamentals/crud/write-operations>
Can probably just be Read / Write

2024-11-11 15:40 UTC, mongoKart commented on source/usage-examples.txt
> +   Delete Operations </usage-examples/delete-operations>
Can probably remove Operations for these four

2024-11-11 15:40 UTC, mongoKart commented on source/fundamentals/builders.txt
> +   Updates </fundamentals/builders/updates>
These titles feel awkward. Even though they match the name of the class and the page, I'd go with something more intuitive:

```suggestion
   Aggregation </fundamentals/builders/aggregates>
   Filters </fundamentals/builders/filters>
   Indexes </fundamentals/builders/indexes>
   Projection </fundamentals/builders/projections>
   Sort </fundamentals/builders/sort>
   Update </fundamentals/builders/updates>
```

2024-11-13 20:56 UTC, sarahemlin requested changes
LGTM with Mike's suggested changes

2024-11-21 15:39 UTC, sarahemlin approved these changes

2024-11-21 19:36 UTC, merged